### ISSUE TITLE
Не корректно работает модуль после обноления

### ISSUE THREAD

**Issue by UksusoFF** [ulogin/ulogin-phpBB#4]
Обновил форум с 3.0.8 до 3.0.12.
Повторно установил uLogin
И что-то не хочет меня авторизовывать через соц сети. Редиректит на страницу регистрации форума после авторизации. Может нужно какие-то еще действия проделать?

**Comment by UksusoFF** [comment]
Походу таже проблема:
http://ulogin.reformal.ru/proj/?ia=674704

**Comment by UksusoFF** [comment]
Если вернуть как [было](https://github.com/ulogin/ulogin-phpBB/commit/85f253b0b5228fbb8be3bc96a5b217a2ed4f2066#diff-7291bb344ee5c3d22dc69a1dddfb3143) до этого коммита, то авторизует. Но потом редиректит на главную где снова не авторизованный пользователь получается.

**Comment by UksusoFF** [comment]
Так, ладно, посли очистки кук все встало на свои места.
Но тот коммит все таки ломает модуль...

**Comment by ulogin-team** [comment]
Протестировали со всех сторон - да, действительно накосячили, извиняемся.
Отменили неудачный коммит, спасибо за то что обратили внимание!
